##
# My First Ansible Playbook
##
---
- name: My first playbook
  hosts: localhost
  tasks:
  - name: Install my dev tools
    ansible.builtin.package:
      name: 
       - git
       - python3
      state: latest